channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.0.1
- pip:
  - mlflow==2.14.0
  - autogluon-common==1.3.1
  - autogluon-core==1.3.1
  - autogluon-features==1.3.1
  - autogluon-tabular==1.3.1
  - autogluon-timeseries==1.3.1
  - cloudpickle==3.1.1
  - gluonts==0.16.2
  - numpy==1.26.4
  - orjson==3.11.1
  - packaging==24.2
  - pandas==2.2.3
  - psutil==7.0.0
  - pyarrow==15.0.2
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - torch==2.6.0
name: mlflow-env
